#spring.application.name=E-Commerce Application
#spring.h2.console.enable=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
spring:
  application:
    name: E-Commerce Application
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enable: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update